"""ALLIE v1 — post metadata suggestions. Grounded in brand voice + platform norms,
generated by Claude. (Full RSS/agentic/deep-dive ALLIE comes later; this is the
useful v1 that needs no new infrastructure.)"""

import json
import re
from typing import Optional

from .brands import _PRESETS
from .llm import get_llm

PLATFORM_NOTES = {
    "tiktok": "Short punchy caption (1-2 lines), hook in the first line; 3-5 trending + niche hashtags; first comment can hold extra hashtags.",
    "youtube": "A compelling TITLE (<70 chars, keyword early) + a 2-4 sentence description; 3-6 hashtags; first comment optional.",
    "instagram": "Caption with a hook then value; 5-10 hashtags mixing broad + niche; the hashtag block can go in the first comment; emojis ok.",
    "facebook": "Conversational caption; few hashtags (1-3); link-friendly.",
    "linkedin": "Professional, value-first caption (2-4 short paragraphs); 3-5 hashtags; no first-comment hashtag spam.",
    "x": "Concise caption (<=270 chars), punchy; 1-3 hashtags.",
}


def _parse_json(raw: str) -> dict:
    text = raw.strip()
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(0))
        except Exception:
            pass
    return {}


def suggest(brand: str, persona: Optional[str], topic: str, script: Optional[str], platform: str) -> dict:
    b = _PRESETS["brands"].get((brand or "").lower(), {})
    tone = b.get("tone_rules", "")
    note = PLATFORM_NOTES.get((platform or "").lower(), PLATFORM_NOTES["tiktok"])
    system = (
        "You are ALLIE, the distribution strategist for the RMG brand ecosystem. Produce social "
        "post metadata that fits the brand voice and the platform's norms, optimized for reach.\n"
        f"Brand voice rules: {tone[:600]}\n"
        f"Platform ({platform}) norms: {note}\n"
        "Return STRICT JSON only (no prose, no code fence) with keys: "
        'title (string, "" if N/A), caption (string), hashtags (array of strings WITHOUT the # sign), '
        'first_comment (string, "" if none), audience (short string naming the target audience).'
    )
    user = f"Topic: {topic}\n" + (f"Persona: {persona}\n" if persona else "") + f"\nScript/transcript:\n{(script or '')[:2000]}"
    raw = get_llm().complete(system=system, user=user, max_tokens=700)
    data = _parse_json(raw)
    return {
        "title": (data.get("title") or "")[:100],
        "caption": data.get("caption") or "",
        "hashtags": [str(h).lstrip("#").strip() for h in (data.get("hashtags") or []) if str(h).strip()][:15],
        "first_comment": data.get("first_comment") or "",
        "audience": data.get("audience") or "",
    }
